############
## Inputs ##
############

input {
    kb_layout = us

    follow_mouse = 1
    sensitivity = 0.25 
	scroll_method = 2fg
    touchpad {
        natural_scroll = true
    }
}


##############
## Gestures ## 
##############

gesture = 3, horizontal, workspace, scale : 0.75
gesture = 3, down, special, magic
gesture = 3, up, fullscreen

gestures {
	workspace_swipe_touch = true
	workspace_swipe_distance = 100
}
