source = ~/.dotfiles/local.config


################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=eDP-1,preferred,auto,auto
monitor=DP-3,3840x2160@60,auto-center-up,2.4


###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = dolphin
$menu = wofi --show drun
$browser = firefox


#################
### AUTOSTART ###
#################

exec-once = waybar & hyprpaper & swaync & hypridle
exec-once = kwalletd5


#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24


#####################
### LOOK AND FEEL ###
#####################

source = ~/.dotfiles/hypr/windows.conf


#############
### INPUT ###
#############

source = ~/.dotfiles/hypr/input.conf


################
### BINDINGS ###
################

source = ~/.dotfiles/hypr/binds.conf	# Source bindings

##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
